#:kivy 2.1.0

<ScreenMenu>:
    MDBoxLayout:
        orientation: "vertical"

		# header layout
        MDBoxLayout:
            id: header_layout
            orientation: "horizontal"
            padding: 20
			spacing: 20
			size_hint_y: 0.2
			md_bg_color: "#111111"
                    
            Image:
                id: logo
                source:'assets/images/logo-trb.png'
                size_hint_x: 0.15
                allow_stretch: True 

			MDBoxLayout:
				orientation: "vertical"
				size_hint_x: 0.7

				MDLabel:
					id: lb_title            
					text: "VEHICLE INSPECTION INTEGRATION MANAGEMENT SYSTEM"
					halign: "left"
					valign: "middle"
					font_style: 'H4'
					theme_text_color: "Custom"
					text_color: "#FFFFFF"

				MDLabel:
					id: lb_subtitle            
					text: "SPEED & SIDE SLIP METER"
					halign: "left"
					valign: "middle"
					font_style: 'H5'
					theme_text_color: "Custom"
					text_color: "#FFFFFF"

			MDBoxLayout:
				orientation: "vertical"
				size_hint_x: 0.15

				MDLabel:
					id: lb_time
					text: "12:34:00"
					halign: "center"
					valign: "middle"
					font_style: 'H6'
					theme_text_color: "Custom"
					text_color: "#FFFFFF"

				MDLabel:
					id: lb_date
					text: "17/08/2024"
					halign: "center"
					valign: "middle"
					font_style: 'H6'
					theme_text_color: "Custom"
					text_color: "#FFFFFF"

				MDLabel:
					id: lb_operator
					text: "Nama Operator"
					halign: "center"
					valign: "middle"
					font_style: 'H6'
					theme_text_color: "Custom"
					text_color: "#FFFFFF"

				MDLabel:
					id: lb_comm
					text: "Status : Disconnected"
					halign: "center"
					valign: "middle"
					font_style: 'H6'
					theme_text_color: "Custom"

		# main layout
		MDBoxLayout:
			id: layout_main
			orientation: "horizontal"
			size_hint_y: 0.7
			padding:20
			spacing:20

			MDBoxLayout:
				id: layout_display
				orientation: "horizontal"

				MDBoxLayout:
					orientation: "vertical"
					size_hint_x: 0.5
					padding:20
					spacing:20

					MDBoxLayout:
						orientation: "vertical"
						size_hint_y: 0.75
						spacing:10

						MDLabel:
							text: "IDENTITAS KENDARAAN"
							halign: "center"
							valign: "middle"
							font_style: 'H6'

						MDBoxLayout:
							orientation: "horizontal"
							MDLabel:
								text: "No. Antrian"
								halign: "left"
								valign: "middle"
								font_style: 'H6'
							MDLabel:
								id: lb_no_antri
								halign: "left"
								valign: "middle"
								font_style: 'H6'

						MDBoxLayout:
							orientation: "horizontal"
							MDLabel:
								text: "No. Polisi"
								halign: "left"
								valign: "middle"
								font_style: 'H6'
							MDLabel:
								id: lb_no_pol
								halign: "left"
								valign: "middle"
								font_style: 'H6'

						MDBoxLayout:
							orientation: "horizontal"
							MDLabel:
								text: "No. Uji"
								halign: "left"
								valign: "middle"
								font_style: 'H6'
							MDLabel:
								id: lb_no_uji
								halign: "left"
								valign: "middle"
								font_style: 'H6'

						MDBoxLayout:
							orientation: "horizontal"
							MDLabel:
								text: "Status Uji"
								halign: "left"
								valign: "middle"
								font_style: 'H6'
							MDLabel:
								id: lb_sts_uji
								halign: "left"
								valign: "middle"
								font_style: 'H6'

						MDBoxLayout:
							orientation: "horizontal"
							MDLabel:
								text: "Merk"
								halign: "left"
								valign: "middle"
								font_style: 'H6'
							MDLabel:
								id: lb_merk
								halign: "left"
								valign: "middle"
								font_style: 'H6'

						MDBoxLayout:
							orientation: "horizontal"
							MDLabel:
								text: "Type"
								halign: "left"
								valign: "middle"
								font_style: 'H6'
							MDLabel:
								id: lb_type
								halign: "left"
								valign: "middle"
								font_style: 'H6'

						MDBoxLayout:
							orientation: "horizontal"
							MDLabel:
								text: "Jenis Kendaraan"
								halign: "left"
								valign: "middle"
								font_style: 'H6'
							MDLabel:
								id: lb_jns_kend
								halign: "left"
								valign: "middle"
								font_style: 'H6'

						MDBoxLayout:
							orientation: "horizontal"
							MDLabel:
								text: "JBB"
								halign: "left"
								valign: "middle"
								font_style: 'H6'
							MDLabel:
								id: lb_jbb
								halign: "left"
								valign: "middle"
								font_style: 'H6'

						MDBoxLayout:
							orientation: "horizontal"
							MDLabel:
								text: "Berat Kosong"
								halign: "left"
								valign: "middle"
								font_style: 'H6'
							MDLabel:
								id: lb_brt_ksg
								halign: "left"
								valign: "middle"
								font_style: 'H6'

						MDBoxLayout:
							orientation: "horizontal"
							MDLabel:
								text: "Bahan Bakar"
								halign: "left"
								valign: "middle"
								font_style: 'H6'
							MDLabel:
								id: lb_bhn_bkr
								halign: "left"
								valign: "middle"
								font_style: 'H6'

						MDBoxLayout:
							orientation: "horizontal"
							MDLabel:
								text: "Warna"
								halign: "left"
								valign: "middle"
								font_style: 'H6'
							MDLabel:
								id: lb_warna
								halign: "left"
								valign: "middle"
								font_style: 'H6'

					MDLabel:
						id: lb_test_result
						halign: "center"
						valign: "middle"
						theme_text_color: "Custom"
						font_style: 'H3'
						size_hint_y: 0.25

				MDBoxLayout:
					orientation: "vertical"
					size_hint_x: 0.5

					MDBoxLayout:
						orientation: "horizontal"
						size_hint_y: 0.1

						MDLabel:
							text: "MENU PENGUJIAN"
							halign: "center"
							valign: "middle"
							font_style: 'H6'
						
					MDBoxLayout:
						orientation: "vertical"
						size_hint_y: 0.8
						padding: 0, 40

						MDBoxLayout:
							orientation: "vertical"
							size_hint_x: 1
							spacing: 30
							
							MDCard:
								size_hint: 1, 0.3
								ripple_behavior: True
								on_press: root.exec_start_speed()
								md_bg_color: "#4471C4"
								padding: 10
								Image:
									source:'assets/images/icon-speed.png'
									size_hint_x: 0.3
									allow_stretch: True 
								MDLabel:
									text: "SPEED TEST"
									theme_text_color: "Custom"
									text_color: "#EEEEEE"
									halign: "center"

							MDCard:
								size_hint: 1, 0.3
								ripple_behavior: True
								on_press: root.exec_start_sideslip()
								md_bg_color: "#555555"
								padding: 10
								Image:
									source:'assets/images/icon-sideslip.png'
									size_hint_x: 0.3
									allow_stretch: True 
								MDLabel:
									text: "SIDESLIP TEST"
									theme_text_color: "Custom"
									text_color: "#EEEEEE"
									halign: "center"

					MDBoxLayout:
						orientation: "horizontal"
						spacing: 20
						size_hint_y: 0.1

						MDRectangleFlatIconButton:
							id: bt_back
							text: "KEMBALI"
							icon: "arrow-left"
							theme_text_color: "Custom"
							text_color: "#EEEEEE"
							md_bg_color: "4471C4"
							size_hint_x: 1
							on_press: root.exec_navigate_main()

		# footer layout
        MDBoxLayout:
            orientation: "horizontal"
			size_hint_y: 0.1

			MDBoxLayout:
				orientation: "horizontal"
				padding: 20
				spacing: 20
				md_bg_color: "#4471C4"
				size_hint_x: 0.4
				
				AsyncImage:
					id: img_pemkab
					source:'assets/images/logo-sorong.png'
					size_hint_x: 0.1
					allow_stretch: True  

				AsyncImage:
					id: img_dishub
					source:'assets/images/logo-dishub.png'
					size_hint_x: 0.1
					allow_stretch: True  

				MDBoxLayout:
					orientation: "vertical"
					size_hint_x: 0.8

					MDLabel:
						id: lb_pemkab
						text: "PEMERINTAH KABUPATEN SORONG"
						halign: "left"
						valign: "middle"
						theme_text_color: "Custom"
						text_color: "#EEEEEE"						
						font_style: 'Subtitle1'

					MDLabel:
						id: lb_dishub
						text: "DINAS PERHUBUNGAN"
						halign: "left"
						valign: "middle"
						theme_text_color: "Custom"
						text_color: "#EEEEEE"
						font_style: 'Subtitle1'

					MDLabel:
						id: lb_unit			
						text: "UNIT PELAKSANA UJI BERKALA KENDARAAN BERMOTOR"
						halign: "left"
						valign: "middle"
						theme_text_color: "Custom"
						text_color: "#EEEEEE"
						font_style: 'Subtitle1'

					MDLabel:
						id: lb_unit_address
						text: " Klamasen, Distrik Mariat, Kabupaten Sorong, Papua Barat Daya. 98416"
						halign: "left"
						valign: "middle"
						md_bg_color: "#EEEEEE"
						theme_text_color: "Custom"
						text_color: "#000000"
						font_style: 'Subtitle1'

			MDBoxLayout:
				orientation: "vertical"
				padding: 20
				spacing: 20
				md_bg_color: "#FFC000"
				size_hint_x: 0.6

				MDLabel:			
					text: "INFORMASI"
					halign: "left"
					valign: "middle"
					font_style: 'H5'

				MDLabel:
					id: lb_info
					text: "Silahkan pilih nomor Sumbu yang akan di uji kemudian pilih menu jenis pengujian untuk masing masing Sumbu"
					halign: "left"
					valign: "middle"
					font_style: 'H6'