#:kivy 2.1.0

<ScreenCalibration>:
    MDBoxLayout:
        orientation: "vertical"

		# header layout
        MDBoxLayout:
            id: header_layout
            orientation: "horizontal"
            padding: 20
			spacing: 20
			size_hint_y: 0.2
			md_bg_color: "#111111"
                    
            Image:
                id: logo
                source:'assets/images/logo-trb.png'
                size_hint_x: 0.15
                allow_stretch: True 

			MDBoxLayout:
				orientation: "vertical"
				size_hint_x: 0.7

				MDLabel:
					id: lb_title            
					text: "VEHICLE INSPECTION INTEGRATION MANAGEMENT SYSTEM"
					halign: "left"
					valign: "middle"
					font_style: 'H4'
					theme_text_color: "Custom"
					text_color: "#FFFFFF"

				MDLabel:
					id: lb_subtitle            
					text: "SPEED & SIDE SLIP METER"
					halign: "left"
					valign: "middle"
					font_style: 'H5'
					theme_text_color: "Custom"
					text_color: "#FFFFFF"

			MDBoxLayout:
				orientation: "vertical"
				size_hint_x: 0.15

				MDLabel:
					id: lb_time
					text: "12:34:00"
					halign: "center"
					valign: "middle"
					font_style: 'H6'
					theme_text_color: "Custom"
					text_color: "#FFFFFF"

				MDLabel:
					id: lb_date
					text: "17/08/2024"
					halign: "center"
					valign: "middle"
					font_style: 'H6'
					theme_text_color: "Custom"
					text_color: "#FFFFFF"

				MDLabel:
					id: lb_operator
					text: "Nama Operator"
					halign: "center"
					valign: "middle"
					font_style: 'H6'
					theme_text_color: "Custom"
					text_color: "#FFFFFF"

				MDLabel:
					id: lb_comm
					text: "Status : Disconnected"
					halign: "center"
					valign: "middle"
					font_style: 'H6'
					theme_text_color: "Custom"

		# main layout
		MDBoxLayout:
			id: layout_main
			orientation: "vertical"
			size_hint_y: 0.7
			padding:20
			spacing:20

			MDBoxLayout:
				id: layout_display
				orientation: "horizontal"
						
				MDBoxLayout:
					orientation: "vertical"
					size_hint_x: 0.5
					padding:20
					spacing:15

					MDBoxLayout:
						orientation: "vertical"
						size_hint_y: 0.5
						MDLabel:
							text: "KALIBRASI SPEEDO"
							halign: "center"
							valign: "middle"
							font_style: 'H5'

						MDLabel:
							text: "Realtime:"
							halign: "center"
							valign: "middle"
							font_style: 'H3'

						MDLabel:
							id:lb_speed_val
							text: "..."
							halign: "center"
							valign: "middle"
							font_style: 'H1'
					
					MDBoxLayout:
						orientation: "vertical"
						size_hint_y: 0.5
						spacing: 15
						MDRectangleFlatIconButton:
							id: bt_exec_calibrate_default_ppr_speed
							type: "large"
							icon: "play"
							size_hint_x: 0.3
							size_hint_y: 0.2
							text:"RESET SETELAN"
							text_color: "#EEEEEE"
							md_bg_color: "#4471C4"
							font_style: 'H6'
							on_press: root.exec_calibrate_default_ppr_speed()
							on_release: root.rel_calibrate_default_ppr_speed()	

						MDBoxLayout:
							orientation: "horizontal"
							size_hint_y: 0.2
							MDLabel:
								text: "Kalibrasi PPR Encoder"
								halign: "left"
								valign: "middle"
								font_style: 'H6'
								size_hint_x: 0.3

							MDTextField:
								id: tx_calibrate_ppr_speed
								hint_text: "PPR Encoder"
								halign: "left"
								valign: "middle"
								font_style: 'H6'
								size_hint_x: 0.4
								type: "number"
								input_filter: 'int'
								text_color_focus: "#4471C4"
								on_text_validate: root.exec_calibrate_ppr_speed()
							
							MDRectangleFlatIconButton:
								id: bt_exec_calibrate_ppr_speed
								type: "large"
								size_hint_x: 0.3
								icon: "gauge"
								text:"KALIBRASI"
								text_color: "#EEEEEE"
								md_bg_color: "#2CA02C"
								font_style: 'H6'
								on_press: root.exec_calibrate_ppr_speed()

						MDBoxLayout:
							orientation: "horizontal"
							size_hint_y: 0.6	

				MDBoxLayout:
					orientation: "vertical"
					size_hint_x: 0.5
					padding:20
					spacing:15

					MDBoxLayout:
						orientation: "vertical"
						size_hint_y: 0.5
						MDLabel:
							text: "KALIBRASI SIDESLIP"
							halign: "center"
							valign: "middle"
							font_style: 'H5'

						MDLabel:
							text: "Realtime:"
							halign: "center"
							valign: "middle"
							font_style: 'H3'


						MDLabel:
							id:lb_sideslip_val
							text: "..."
							halign: "center"
							valign: "middle"
							font_style: 'H1'
					
					MDBoxLayout:
						orientation: "vertical"
						size_hint_y: 0.5
						spacing: 15

						MDRectangleFlatIconButton:
							id: bt_exec_calibrate_default_ppr_sideslip
							type: "large"
							icon: "play"
							size_hint_x: 0.3
							size_hint_y: 0.2
							text:"RESET SETELAN"
							text_color: "#EEEEEE"
							md_bg_color: "#4471C4"
							font_style: 'H6'
							on_press: root.exec_calibrate_default_ppr_sideslip()
							on_release: root.rel_calibrate_default_ppr_sideslip()	

						MDBoxLayout:
							orientation: "horizontal"
							size_hint_y: 0.2
							MDLabel:
								text: "Kalibrasi PPR Encoder"
								halign: "left"
								valign: "middle"
								font_style: 'H6'
								size_hint_x: 0.3

							MDTextField:
								id: tx_calibrate_ppr_sideslip
								hint_text: "PPR Encoder"
								halign: "left"
								valign: "middle"
								font_style: 'H6'
								size_hint_x: 0.4
								type: "number"
								input_filter: 'int'
								text_color_focus: "#4471C4"
								on_text_validate: root.exec_calibrate_ppr_sideslip()								
							
							MDRectangleFlatIconButton:
								id: bt_exec_calibrate_ppr_sideslip
								type: "large"
								size_hint_x: 0.3
								icon: "gauge"
								text:"KALIBRASI"
								text_color: "#EEEEEE"
								md_bg_color: "#2CA02C"
								font_style: 'H6'
								on_press: root.exec_calibrate_ppr_sideslip()

						MDBoxLayout:
							orientation: "horizontal"
							size_hint_y: 0.6								
	
			MDBoxLayout:
				orientation: "horizontal"
				spacing: 20
				size_hint_y: 0.02

				MDRectangleFlatIconButton:
					id: bt_cylinder_up
					text: "CYLINDER"
					icon: "arrow-up"
					theme_text_color: "Custom"
					text_color: "#EEEEEE"
					md_bg_color: "#FF2A2A"
					size_hint_x: 0.3
					on_press: root.exec_cylinder_up()
					on_release: root.exec_cylinder_stop()

				MDRectangleFlatIconButton:
					id: bt_cylinder_down
					text: "CYLINDER"
					icon: "arrow-down"
					theme_text_color: "Custom"
					text_color: "#EEEEEE"
					md_bg_color: "#2CA02C"
					size_hint_x: 0.3
					on_press: root.exec_cylinder_down()
					on_release: root.exec_cylinder_stop()
					
				MDRectangleFlatIconButton:
					id: bt_back
					text: "KEMBALI"
					icon: "arrow-left"
					theme_text_color: "Custom"
					text_color: "#EEEEEE"
					md_bg_color: "4471C4"
					size_hint_x: 0.3
					on_press: root.exec_navigate_main()

		# footer layout
        MDBoxLayout:
            orientation: "horizontal"
			size_hint_y: 0.1

			MDBoxLayout:
				orientation: "horizontal"
				padding: 20
				spacing: 20
				md_bg_color: "#4471C4"
				size_hint_x: 0.4
				
				AsyncImage:
					id: img_pemkab
					source:'assets/images/logo-sorong.png'
					size_hint_x: 0.1
					allow_stretch: True  

				AsyncImage:
					id: img_dishub
					source:'assets/images/logo-dishub.png'
					size_hint_x: 0.1
					allow_stretch: True  

				MDBoxLayout:
					orientation: "vertical"
					size_hint_x: 0.8

					MDLabel:
						id: lb_pemkab
						text: "PEMERINTAH KABUPATEN SORONG"
						halign: "left"
						valign: "middle"
						theme_text_color: "Custom"
						text_color: "#EEEEEE"						
						font_style: 'Subtitle1'

					MDLabel:
						id: lb_dishub
						text: "DINAS PERHUBUNGAN"
						halign: "left"
						valign: "middle"
						theme_text_color: "Custom"
						text_color: "#EEEEEE"
						font_style: 'Subtitle1'

					MDLabel:
						id: lb_unit			
						text: "UNIT PELAKSANA UJI BERKALA KENDARAAN BERMOTOR"
						halign: "left"
						valign: "middle"
						theme_text_color: "Custom"
						text_color: "#EEEEEE"
						font_style: 'Subtitle1'

					MDLabel:
						id: lb_unit_address
						text: " Klamasen, Distrik Mariat, Kabupaten Sorong, Papua Barat Daya. 98416"
						halign: "left"
						valign: "middle"
						md_bg_color: "#EEEEEE"
						theme_text_color: "Custom"
						text_color: "#000000"
						font_style: 'Subtitle1'

			MDBoxLayout:
				orientation: "vertical"
				padding: 20
				spacing: 20
				md_bg_color: "#FFC000"
				size_hint_x: 0.6

				MDLabel:			
					text: "INFORMASI"
					halign: "left"
					valign: "middle"
					font_style: 'H5'

				MDLabel:
					id: lb_info
					text: ""
					halign: "left"
					valign: "middle"
					font_style: 'H6'